name: aprende_app
description: Un proyecto Flutter nuevo para PDFs estilo Espacio Mayor.
publish_to: 'none'


environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.9
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  flutter_pdfview: ^1.2.7

  
  syncfusion_flutter_pdfviewer: ^31.2.10

  
  http: ^1.2.0

  
  go_router: ^14.8.1

  cupertino_icons: ^1.0.6
  animations: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
